### ISSUE TITLE
offtop

### ISSUE THREAD

**Issue by pomazanbohdan** [webyaml/core#5]
http://www.tachyonic.org/

**Comment by webyaml** [comment]
that is a nice project that has a lot of overlaps with webyaml.  I think the key difference is the focus of the projects.

> Purposely built for large operators such as mobile telephone operators, commercial and home broadband providers, tier 1 network operators, large data center and cloud providers by experienced network engineers for network engineers.

Whereas webyaml was built to have a small footprint and low barriers to entry.

Thanks for sharing
