### ISSUE TITLE
Error in Docs

### ISSUE THREAD

**Issue by ars1979** [webyaml/core#6]
I get the following error when trying to access the Markdown page:
<type 'exceptions.AttributeError'> at /docs/reference/elements/markdown
'str' object has no attribute 'get'
Python | /opt/webyaml/sites/webyaml.com/core/classes/content.py in __init__, line 74
-- | --
GET http://webyaml.com/docs/reference/elements/markdown

**Comment by webyaml** [comment]
Thanks for letting us know.  The page has been updated and is working now.
